version: '2.1'

services:

  nightwatch:
    build:
      context: .
    volumes:
      - /data/www/ui-testing-suite/tests/:/home/docker/app/tests/
    environment:
      NODE_ENV: test
    depends_on:
      - hub

  selenium:
    image: elgalu/selenium

  hub:
    image: "dosel/zalenium"
    tty: true
    volumes:
#      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    hostname: hub
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 4
            --maxDockerSeleniumContainers 8
            --screenWidth 1920 --screenHeight 1080
            --timeZone "Europe/Rome"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_TIMEOUT: 120000
      VIRTUAL_HOST: selenium.hub.docker